---

- name: store host facts
  blockinfile:
    dest: .ansible/facts.d/{{ app_name }}.fact
    marker: "{mark}"
    marker_begin: '{'
    marker_end: '}'
    create: yes
    block: |
        "env_color": "{{ _app_next_color }}",
        "instances_count": "{{ app_instances_count }}",
        "version": "{{ app_version }}"

- name: stop or remove old env containers
  docker_container:
    name: "{{ app_name }}_{{ _app_prev_color }}_{{ item }}"
    state: "{{ app_old_containers_treatment_type }}"
  loop: "{{ range(_app_prev_count | int) | list }}"
  ignore_errors: yes
  when:
    - not _app_first_run
    - app_version != _app_prev_version
    - app_old_containers_treatment_enabled
  vars:
    ansible_python_interpreter: ~/.pyenv/versions/2.7.18/bin/python
